import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import 'easymde/dist/easymde.min.css'

import { Toaster } from "@/components/ui/toaster"

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EcoMinds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="pt-br">
        <body
          className={`${jakartaSans.className} light antialiased`}
        >
          {children}
          <Toaster />
        </body>
      </html>
  );
}
